#!/usr/bin/env bash
# design-sync prebuild for CorioScan (run before the converter; this is cfg.buildCmd).
# CorioScan is an app, not a published component library — its shadcn/ui components
# live in client/src/components/ui and ship no dist or .d.ts. This script produces
# everything the converter needs as build inputs, all under .design-sync/dslib/:
#   1. _ds_entry.tsx  — bundle entry: re-exports every ui component (→ window.CorioScan)
#   2. index.d.ts     — types barrel: the 47 curated primaries (drives the component list)
#   3. types/**       — real .d.ts emitted by tsc (gives the extractor true prop contracts)
#   4. compiled.css   — Tailwind theme compiled to a static stylesheet (vars + utilities)
# Generated outputs are gitignored; this script + config.json + dslib/{package.json,
# tsconfig.dts.json} are the durable seed. Idempotent.
set -euo pipefail
cd "$(dirname "$0")/.."          # repo root
DSLIB=".design-sync/dslib"

# ── 1 + 2. generate bundle entry and types barrel from the ui dir ────────────
node --input-type=module <<'NODE'
import { writeFileSync, readdirSync } from "node:fs";
const uiDir = "client/src/components/ui";
const files = readdirSync(uiDir).filter(f => f.endsWith(".tsx")).map(f => f.replace(/\.tsx$/, "")).sort();

const entry =
`// GENERATED by .design-sync/prebuild.sh — do not edit (gitignored).
// Bundle entry (synth mode): re-exports every shadcn/ui component so esbuild
// bundles them into one IIFE on window.CorioScan. Internal "@/…" imports
// resolve via ../../tsconfig.json.
` + files.map(f => `export * from "../../client/src/components/ui/${f}";`).join("\n") + "\n";
writeFileSync(".design-sync/dslib/_ds_entry.tsx", entry);

// Curated primary component per file — the ones that get a card / .d.ts contract.
// (All sub-parts remain importable from window.CorioScan via the bundle entry.)
const primary = {
  accordion:"Accordion","alert-dialog":"AlertDialog",alert:"Alert","aspect-ratio":"AspectRatio",
  avatar:"Avatar",badge:"Badge",breadcrumb:"Breadcrumb",button:"Button",calendar:"Calendar",
  card:"Card",carousel:"Carousel",chart:"ChartContainer",checkbox:"Checkbox",collapsible:"Collapsible",
  command:"Command","context-menu":"ContextMenu",dialog:"Dialog",drawer:"Drawer","dropdown-menu":"DropdownMenu",
  form:"Form","hover-card":"HoverCard","input-otp":"InputOTP",input:"Input",label:"Label",menubar:"Menubar",
  "navigation-menu":"NavigationMenu",pagination:"Pagination",popover:"Popover",progress:"Progress",
  "radio-group":"RadioGroup",resizable:"ResizablePanelGroup","scroll-area":"ScrollArea",select:"Select",
  separator:"Separator",sheet:"Sheet",sidebar:"Sidebar",skeleton:"Skeleton",slider:"Slider",switch:"Switch",
  table:"Table",tabs:"Tabs",textarea:"Textarea",toast:"Toast",toaster:"Toaster","toggle-group":"ToggleGroup",
  toggle:"Toggle",tooltip:"Tooltip"
};
const missing = files.filter(f => !primary[f]);
if (missing.length) console.error("[prebuild] WARNING unmapped ui files:", missing.join(", "));
const barrel =
`// GENERATED by .design-sync/prebuild.sh — do not edit (gitignored).
// Types barrel: the design-sync converter reads this as the package "types"
// entry. Re-exports the curated primary components from the tsc-emitted
// declarations in ./types/, giving the extractor real prop contracts.
` + Object.entries(primary).map(([f, n]) => `export { ${n} } from "./types/components/ui/${f}";`).join("\n") + "\n";
writeFileSync(".design-sync/dslib/index.d.ts", barrel);
console.error(`[prebuild] generated _ds_entry.tsx (${files.length} files) + index.d.ts (${Object.keys(primary).length} primaries)`);
NODE

# ── 3. emit real .d.ts for every ui component ────────────────────────────────
rm -rf "$DSLIB/types"
node_modules/.bin/tsc -p "$DSLIB/tsconfig.dts.json"
echo "[prebuild] tsc emitted $(find "$DSLIB/types/components/ui" -name '*.d.ts' | wc -l | tr -d ' ') component declarations"

# ── 4. compile the Tailwind theme to a static stylesheet ─────────────────────
node_modules/.bin/tailwindcss \
  -c tailwind.config.ts \
  -i client/src/index.css \
  -o "$DSLIB/compiled.css" \
  --content "./client/src/components/ui/**/*.{ts,tsx},./.design-sync/previews/**/*.{ts,tsx}" \
  2>&1 | tail -1
# Brand fonts load at runtime via Google Fonts; keep the @import first (valid CSS).
FONT_IMPORT="@import url('https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,400..800&family=Hanken+Grotesk:ital,wght@0,400..800;1,400..700&display=swap');"
printf '%s\n' "$FONT_IMPORT" | cat - "$DSLIB/compiled.css" > "$DSLIB/compiled.css.tmp"
mv "$DSLIB/compiled.css.tmp" "$DSLIB/compiled.css"
echo "[prebuild] compiled.css: $(wc -c < "$DSLIB/compiled.css" | tr -d ' ') bytes, font @import prepended"
