import { Case } from '@/types/schema';
import { format } from 'date-fns';
import { tr, enUS } from 'date-fns/locale';

interface ReportGeneratorProps {
    caseData: Case;
    language: 'tr' | 'en';
}

export const generateReportHtml = ({ caseData, language }: ReportGeneratorProps): string => {
    const isTr = language === 'tr';
    const dateLocale = isTr ? tr : enUS;
    const date = caseData.createdAt
        ? format(new Date(caseData.createdAt), 'dd MMMM yyyy, HH:mm', { locale: dateLocale })
        : '-';

    const logo = "https://i.imgur.com/4L7Z6lX.png"; // Placeholder or use base64 if available, for now using text or simple styling
    // Ideally we would use a real logo URL or base64

    // Translations
    const t = {
        reportTitle: isTr ? 'Dermatolojik Analiz Raporu' : 'Dermatological Analysis Report',
        date: isTr ? 'Tarih' : 'Date',
        caseId: isTr ? 'Vaka No' : 'Case ID',
        patientInfo: isTr ? 'Hasta Bilgileri' : 'Patient Information',
        lesionLocation: isTr ? 'Lezyon Konumu' : 'Lesion Location',
        symptoms: isTr ? 'Belirtiler' : 'Symptoms',
        duration: isTr ? 'Süre' : 'Duration',
        medicalHistory: isTr ? 'Tıbbi Geçmiş' : 'Medical History',
        notSpecified: isTr ? 'Belirtilmedi' : 'Not specified',
        lesionImages: isTr ? 'Lezyon Görselleri' : 'Lesion Images',
        analysisResults: isTr ? 'Analiz Sonuçları' : 'Analysis Results',
        confidence: isTr ? 'Güven Skoru' : 'Confidence Score',
        keyFeatures: isTr ? 'Temel Bulgular' : 'Key Findings',
        recommendations: isTr ? 'Öneriler' : 'Recommendations',
        disclaimer: isTr
            ? 'Bu rapor yapay zeka destekli bir ön analizdir. Kesinlikle tıbbi teşhis yerine geçmez. Lütfen sonuçları bir dermatolog ile paylaşınız.'
            : 'This report is an AI-assisted preliminary analysis. It does not replace a medical diagnosis. Please share these results with a dermatologist.',
        generatedBy: isTr ? 'Rapor Oluşturan' : 'Report Generated By',
        footer: 'Corium Scan - AI Powered Dermatology Assistant'
    };

    const primaryColor = '#007AFF'; // Blue
    const secondaryColor = '#5856D6'; // Purple

    // Process Images
    const imagesHtml = (caseData.imageUrls || [caseData.imageUrl]).filter(Boolean).map(url => `
        <div class="image-container">
            <img src="${url}" alt="Lesion" />
        </div>
    `).join('');

    // Process Diagnosis - Use selected provider's diagnoses
    const selectedProvider = caseData.selectedAnalysisProvider || 'gemini';
    const selectedDiagnoses = selectedProvider === 'openai'
        ? caseData.openaiAnalysis?.diagnoses || []
        : caseData.geminiAnalysis?.diagnoses || [];
    const diagnosesHtml = selectedDiagnoses.map((d, index) => {
        // Handle confidence score: if > 1, assume 0-100, if <= 1, assume 0.0-1.0
        const score = d.confidence > 1 ? d.confidence : d.confidence * 100;

        return `
        <div class="diagnosis-card">
            <div class="diagnosis-header">
                <span class="rank">#${index + 1}</span>
                <span class="diagnosis-name">${d.name}</span>
                <span class="confidence">${score.toFixed(1)}% ${t.confidence}</span>
            </div>
            
            ${d.description ? `<p class="description">${d.description}</p>` : ''}
            
            ${d.keyFeatures ? `
                <div class="section">
                    <strong>${t.keyFeatures}:</strong>
                    <ul>
                        ${d.keyFeatures.map(f => `<li>${f}</li>`).join('')}
                    </ul>
                </div>
            ` : ''}

            ${d.recommendations ? `
                <div class="section">
                    <strong>${t.recommendations}:</strong>
                    <ul>
                        ${d.recommendations.map(r => `<li>${r}</li>`).join('')}
                    </ul>
                </div>
            ` : ''}
        </div>
    `}).join('');

    return `
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>${t.reportTitle}</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            color: #333;
            line-height: 1.6;
            margin: 0;
            padding: 40px;
        }
        .force-break {
            page-break-before: always;
        }
        .header {
            text-align: center;
            margin-bottom: 40px;
            border-bottom: 2px solid ${primaryColor};
            padding-bottom: 20px;
        }
        .logo-text {
            font-size: 32px;
            font-weight: bold;
            color: ${primaryColor};
            margin: 0;
            letter-spacing: 1px;
        }
        .sub-logo {
            font-size: 14px;
            color: ${secondaryColor};
            text-transform: uppercase;
            letter-spacing: 3px;
            margin-top: 5px;
        }
        .report-meta {
            margin-top: 20px;
            font-size: 14px;
            color: #666;
            display: flex;
            justify-content: space-between;
        }
        h2 {
            color: ${primaryColor};
            border-bottom: 1px solid #eee;
            padding-bottom: 10px;
            margin-top: 30px;
        }
        .info-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 15px;
            margin-bottom: 20px;
        }
        .info-item {
            background: #f9f9f9;
            padding: 10px;
            border-radius: 8px;
        }
        .info-label {
            font-size: 12px;
            color: #666;
            display: block;
            margin-bottom: 4px;
        }
        .info-value {
            font-weight: bold;
            font-size: 16px;
        }
        .images-grid {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
            justify-content: center;
            margin: 20px 0;
        }
        .image-container {
            width: 200px;
            height: 200px;
            border: 1px solid #ddd;
            border-radius: 8px;
            overflow: hidden;
            background: #f0f0f0;
        }
        .image-container img {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }
        .diagnosis-card {
            background: #fff;
            border: 1px solid #e0e0e0;
            border-radius: 12px;
            padding: 20px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.05);
            page-break-inside: avoid;
        }
        .diagnosis-header {
            display: flex;
            align-items: center;
            margin-bottom: 15px;
            border-bottom: 1px solid #f0f0f0;
            padding-bottom: 10px;
        }
        .rank {
            background: ${primaryColor};
            color: white;
            width: 30px;
            height: 30px;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: bold;
            margin-right: 15px;
        }
        .diagnosis-name {
            font-size: 20px;
            font-weight: bold;
            flex: 1;
        }
        .confidence {
            background: #e1f5fe;
            color: #0288d1;
            padding: 5px 10px;
            border-radius: 20px;
            font-size: 14px;
            font-weight: bold;
        }
        .description {
            font-style: italic;
            color: #555;
            margin-bottom: 15px;
        }
        .section {
            margin-top: 15px;
        }
        .section strong {
            color: ${secondaryColor};
            display: block;
            margin-bottom: 5px;
        }
        ul {
            margin: 0;
            padding-left: 20px;
        }
        li {
            margin-bottom: 5px;
            color: #444;
        }
        .footer {
            margin-top: 60px;
            text-align: center;
            border-top: 2px solid ${primaryColor};
            padding-top: 30px;
        }
        .disclaimer {
            background: #fff3cd;
            color: #856404;
            padding: 15px;
            border-radius: 8px;
            font-size: 14px;
            margin-bottom: 20px;
            text-align: center;
        }
        .signature {
            font-family: 'Courier New', monospace;
            font-size: 18px;
            font-weight: bold;
            color: ${primaryColor};
            margin-bottom: 5px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="logo-text">Corium Scan</h1>
        <div class="sub-logo">Advanced Dermatology Analysis</div>
        <div class="report-meta">
            <span>${t.caseId}: <strong>${caseData.caseId}</strong></span>
            <span>${t.date}: <strong>${date}</strong></span>
        </div>
    </div>

    <div class="content">
        <h2>${t.patientInfo}</h2>
        <div class="info-grid">
            <div class="info-item">
                <span class="info-label">${t.lesionLocation}</span>
                <span class="info-value">${caseData.lesionLocation || t.notSpecified}</span>
            </div>
            <div class="info-item">
                <span class="info-label">${t.duration}</span>
                <span class="info-value">${caseData.symptomDuration || t.notSpecified}</span>
            </div>
            <div class="info-item">
                <span class="info-label">${t.symptoms}</span>
                <span class="info-value">${caseData.symptoms?.join(', ') || t.notSpecified}</span>
            </div>
            ${caseData.additionalSymptoms ? `
            <div class="info-item">
                <span class="info-label">${t.medicalHistory}</span>
                <span class="info-value">${caseData.additionalSymptoms}</span>
            </div>
            ` : ''}
        </div>

        <h2>${t.lesionImages}</h2>
        <div class="images-grid">
            ${imagesHtml}
        </div>

        <h2 class="force-break">${t.analysisResults}</h2>
        ${diagnosesHtml}
    </div>

    <div class="footer">
        <div class="disclaimer">
            <strong>⚠️ IMPORTANT:</strong> ${t.disclaimer}
        </div>
        <div class="signature">Corium Scan</div>
        <div style="font-size: 12px; color: #999;">${t.generatedBy}: Corio Scan Mobile App</div>
        <div style="font-size: 10px; color: #ccc; margin-top: 20px;">
            ${new Date().getFullYear()} © Corium Scan. All rights reserved.
        </div>
    </div>
</body>
</html>
    `;
};
